- num_channels: 32
  stride: 1
- num_channels: 32
  stride: 1
- num_channels: 32
  stride: 1
- num_channels: 32
  stride: 1
- num_channels: 32
  stride: 1
- num_channels: 64
  stride: 2
- num_channels: 64
  stride: 1
- num_channels: 64
  stride: 1
- num_channels: 64
  stride: 1
- num_channels: 128
  stride: 2
- num_channels: 128
  stride: 1
- num_channels: 128
  stride: 1
- num_channels: 128
  stride: 1